apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-claim
  namespace: project-namespace
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
