apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configMap.yml
  - manifests/knative-service.yml
  - manifests/secret.yml
  - manifests/statefulSet.yml
images:
  - name: log-output-image
    newName: santlemp/log_output:v2-5.5
  - name: ping-pong-image
    newName: santlemp/ping_pong:5.5
namespace: default
   
   
