apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-pvc
  namespace: project-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
