apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/rollout.yml
  - manifests/ingress.yml
  - manifests/service.yml
  - manifests/secret.enc.yml
  - manifests/statefulSet.yml
  - manifests/configMap.yml
  - manifests/persistentVolumeClaim.yaml
  - manifests/analysisTemplate.yml
images:
  - name: frontend
    newName: santlemp/project:frontend-1.9
  - name: backend
    newName: santlemp/project:backend-1.9
namespace: project-flux-namespace
   
