apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/rollout.yml
- manifests/ingress.yml
- manifests/service.yml
- manifests/secret.enc.yml
- manifests/statefulSet.yml
- manifests/configMap.yml
- manifests/persistentVolumeClaim.yaml
- manifests/analysisTemplate.yml
images:
- name: backend
  newName: santlemp/project
  newTag: backend-1288a4000ab4c3d3145d31ca87b5132b17ec8b1b
- name: frontend
  newName: santlemp/project
  newTag: frontend-1288a4000ab4c3d3145d31ca87b5132b17ec8b1b
namespace: project-flux-namespace
