apiVersion: ENC[AES256_GCM,data:B4Q=,iv:YG0hftYwYrbfVxOjBvGhACEGjL1StHhEsXXh1Kh2KA8=,tag:fgpN2GLRuoTXrJk4F9Y+JA==,type:str]
kind: ENC[AES256_GCM,data:SM1sWQvU,iv:oePtpx/wgSrzqdm1CQG36vJJthBA8omcR3yXbo0bCMQ=,tag:ZP51SSjOO0+IAGNeEcFexQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BMtx3VuPWjSLtDxF7ZRW,iv:cBvlB4WxVINYIIrEPiXNl9ACjbd0xtDgTSWlGY/Scvk=,tag:3qydcCupp0VOKlTHfzvwmA==,type:str]
    namespace: ENC[AES256_GCM,data:i6JvzUsVsfnPg+I5gyey76g=,iv:8Sjgp2Zgtu6AwxyP8wgMBXDdoXqjdlPp//BYaNurgmk=,tag:LXAqSZUQL8HBsv7yMQotww==,type:str]
data:
    password: ENC[AES256_GCM,data:3sShJPOCun+iZ660,iv:5EfTXrJ6lRbrp1CP6fz49hqIxVfYI4OYQYYqiwaVKwU=,tag:yjGX9mvna6UNDG9Rt2vdzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w67886g0n7tku3cyyyhd9hl4ecdm4df2tyuuk3kuqjuupy8ld3qqdh5e0f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcU5meER3dDhIR3VrcFg3
            WE4wdks0ZDQvVStWa01rM3VINnhIZG1JS0ZvClJBQys5OCtTY2pIdUVuZmxqZUcy
            YnJrTEdwOHg0ZzJnaStIUTdiR0ZjZ0UKLS0tIEk5Lys4cWgrTlAwZXFmTE41dnJP
            QXRQeXA5bm5CRlhSS3dzdjdoaHBjMHcK3oZCO2+IcllG0zEcR3VVQKFLmnD1uj9o
            skq0Y43v/ici6LNZebYAh/PFAEqEQIURTZj9yyNE30J+PqJxUwrX1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-26T11:46:48Z"
    mac: ENC[AES256_GCM,data:hbTXOo3a/MLxosWOONNj9J6/4jDq5xN3ZaC/MteNx5FaxxfX0JqPeHyHoWeB9AADeCQCfBsDsLHOvk1/9CJ6ALTI3hJAPPbl2n9kiTbeXc1HfZ4ulpr1pmLExO/Uc7Zl8yp7dImGMc7WxuXG7coAj0VHXU83bvxgkE7GzA6/2xM=,iv:CAa+xstz/wPkM6lC9MjTKrBNSjcS5VvTITqVNjRef+c=,tag:xptyCbaUxEbxrZ1ttGW7wA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
